image:
  repository: localstack/localstack
  tag: 0.8.7

service:
  internalPort: 4575
  externalPort: 4575

resources:
  limits:
    cpu: "200m"
    memory: 500Mi
  requests:
    cpu: "100m"
    memory: 100Mi
